### PR TITLE
[FIXED JENKINS-50008] Heap Histogram (all instances by default)

### PR DESCRIPTION
**Pull request by escoem**
https://issues.jenkins-ci.org/browse/JENKINS-50008

Because of live histogram requires a fullgc, by default now is generated for all instances (not only live one).

You could easily configure it by using the system property -Dcom.cloudbees.jenkins.support.impl. HeapUsageHistogram.FULLGC=true (permanent) or by running from Script Console com.cloudbees.jenkins.support.impl. HeapUsageHistogram.FULLGC=true (temporal) if you want to grab live instances.

The histogram component could be easily disabled by using the system property -Dcom.cloudbees.jenkins.support.impl. HeapUsageHistogram.DISABLE=true (permanent) or by running from Script Console com.cloudbees.jenkins.support.impl. HeapUsageHistogram.DISABLE=true (temporal).

I prefer to have something (all instances) than nothing (disable) by default.

Please @jglick @reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
@escoem I still don't see how this addresses my objections in https://github.com/jenkinsci/support-core-plugin/pull/135#issuecomment-370869466 and https://github.com/jenkinsci/support-core-plugin/pull/135#issuecomment-370873737?  

If see any value from the (moderately useless) live heap histograms, there's always the command-line option via JMap.

**Comment by recampbell** [comment]
Perhaps the feature that we want is to optionally collect the heap histogram when generating the bundle?

I think we want a way to do this easily from the support bundle instead of going through the process of getting the user to successfully execute jmap which is always a trial and especially so when the user is under the stress of an outage.

**Comment by christ66** [comment]
>Perhaps the feature that we want is to optionally collect the heap histogram when generating the bundle?

I think the issue is if I don't have access to the UI, then it's impossible to generate a bundle. This seems like a good opportunity to make the `SlowRequests` an extension point to allow for this type of diagnostic information available when the UI isn't accessible.

> If we see any value from garbage-filled (literally) heap histograms, there's always the command-line option via JMap to collect them.

True, but not everyone installs with the JDK and some install with the JRE (iirc JRE doesn't come with the jmap command).

**Comment by varyvol** [comment]
It seems there's not real progress here so closing. Please reopen if you consider this can still move forward.

**Pull request closed without merging**
