### PR TITLE
update quicktheories from 0.25 to 0.26

### PR DESCRIPTION
**Pull request by based2**
https://mvnrepository.com/artifact/org.quicktheories/quicktheories

### CODE REVIEW

**Comment by aheritier** [comment]
No changelog it's painful to see what they changed : https://github.com/quicktheories/QuickTheories/commits/master

**Comment by duemir** [comment]
@aheritier ;) https://github.com/quicktheories/QuickTheories/compare/quicktheories-parent-0.25...quicktheories-parent-0.26

**Comment by varyvol** [comment]
@based2 could you please provide more context on why you want this updated version landed? Is there any behaviour that gets fixed/improved?

**Comment by batmat** [comment]
Closing because of no answer to @varyvol question above. It could look like a supply chain attack as it is.

Thanks!

**Pull request closed without merging**
