### PR TITLE
Test improvement - Consistent naming of JenkinsRule variable

### PR DESCRIPTION
**Pull request by darxriggs**
I have see many different variants like `j`, `r`, `rule`, `jenkins` and `jenkinsRule` among different Jenkins related repositories. `j` seems to be the most common one. Therefore adapting the tests here that used a different variant so far.

### CODE REVIEW

**Comment by varyvol** [comment]
@darxriggs with "the most common one" you mean in this project or in general? "rule" or "r" seem more appealing to me, especially because j.jenkins isn't straightforward to understand.

**Comment by darxriggs** [comment]
In this repository it's like:
```
      2 JenkinsRule rule = new JenkinsRule
      3 JenkinsRule jenkins = new JenkinsRule
      7 JenkinsRule r = new JenkinsRule
     15 JenkinsRule j = new JenkinsRule
```

Over all repositories I have checked out it's like:
```
     ...
     30 JenkinsRule rule = new JenkinsRule
     42 JenkinsRule jenkins = new JenkinsRule
     44 JenkinsRule jenkinsRule = new JenkinsRule
    193 JenkinsRule r = new JenkinsRule
    442 JenkinsRule j = new JenkinsRule
```

**Comment by varyvol** [comment]
@darxriggs fair enough then. I'm closing to retrigger CI:

**Comment by varyvol** [comment]
Tested locally. Merging.

**Pull request merged**
