### PR TITLE
[FIXED JENKINS-31952] Change dockerfile from location.

### PR DESCRIPTION
**Pull request by christ66**

### CODE REVIEW

**Comment by christ66** [comment]
Ops, forgot @reviewbybees

**Comment by mslusarczyk** [comment]
🐝

**Comment by andresrc** [comment]
:bee:

**Comment by aheritier** [comment]
hummm that's crappy/hardcoded :( We couldn't have an extension point to allow vendors to redefine the image coordinate to use ?
Otherwise :bee: better than nothing

**Comment by christ66** [comment]
@aheritier made it a system property.

**Comment by aheritier** [comment]
thanks @christ66 
But a test is failing thus 🐛

**Comment by batmat** [comment]
I think a test would be good to check the behaviour, the code is simple, but so the test would be very easy too.

**Pull request closed without merging**
