### PR TITLE
Print stack trace in logical order

### PR DESCRIPTION
**Pull request by jglick**
See https://github.com/jenkinsci/jenkins/pull/1485.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Successfully tested on the reproduction scenario from [JENKINS-40281](https://issues.jenkins-ci.org/browse/JENKINS-40281):

```
2016-12-12 17:21:29.686-0500 [id=59]	INFO	hudson.model.Run#execute: JENKINS-40281 #1 main build action completed: SUCCESS
2016-12-12 17:21:38.840-0500 [id=35]	WARNING	h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: build.badgeActions in /jenkins/job/JENKINS-40281/. Reason: java.lang.reflect.InvocationTargetException
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
	at hudson.model.Run.getBadgeActions(Run.java:483)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at …lots more…
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jglick** [comment]
Some calls may suffer from same buffering bug as identified in core PR.

**Comment by christ66** [comment]
🐝

**Comment by jglick** [comment]
BTW this was intended to pair with the core PR, but I can be usefully merged on its own—at least the more natural order will now be visible in support logs.

**Pull request merged**
