### PR TITLE
JENKINS-60327 Enable tests on windows

### PR DESCRIPTION
**Pull request by aheritier**
@escoem does it makes sense firstly to do such change to detect this kind of issue ?
cc @MRamonLeon @Dohbedoh 
REF: https://issues.jenkins-ci.org/browse/JENKINS-60327

### CODE REVIEW

**Comment by aheritier** [comment]
you are right @varyvol 
Windows is tested by default (I thought it was linux only).
Why don't we catch JENKINS-60327 ?

**Comment by varyvol** [comment]
@aheritier I didn't mean you to close it. Maybe it was a good opportunity to start building in JDK11 as well.

**Comment by aheritier** [comment]
@varyvol my PR didn't do more than the default behaviour? java 11 could make sense but it is probably something we should also configure by default ?

**Comment by varyvol** [comment]
@aheritier I think using [the recommended configurations|https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPlugin.groovy#L252] would be nice.

**Comment by aheritier** [comment]
@varyvol good idea. I wasn't aware of this recommended config. Let's do it !

**Pull request closed without merging**
