### PR TITLE
Check build queue elements to see if the QueueTaskDispatcher is able to

### PR DESCRIPTION
**Pull request by christ66**
run the builds.

@reviewbybees

### CODE REVIEW

**Comment by aheritier** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Seems the indenting is wrong :bug: 
The log section starts from " * Name of item: ", all other lines under it should be tabulated accordingly.

**Comment by christ66** [comment]
@oleg-nenashev fixed.

**Comment by jglick** [comment]
:bee:

**Pull request merged**
