### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by duemir**
add continuous integration and PR builds for a Jenkins plugin in the jenkinsci organization

@reviewbybees

### CODE REVIEW

**Comment by duemir** [comment]
@batmat @stephenc do you think we are good to go enabling CI for support-core on ci.jenkins.io ?

**Comment by oleg-nenashev** [comment]
We're good. It is a way officially recommended by the Jenkins project

**Comment by duemir** [comment]
@Evildethow merge it ;) ^

**Comment by Evildethow** [comment]
@duemir I don't have write access for some reason. @batmat cc @daniel-beck I should have been setup as maintainer in place of Steven Christou a few months back. Looks like this was never finalised. Can either of you help here?

**Comment by daniel-beck** [comment]
@Evildethow Probably best to go through https://github.com/jenkins-infra/repository-permissions-updater/ so you'll be able to release as necessary; then I can also grant commit access after @christ66 approves.

**Comment by jglick** [comment]
FTR adding a `Jenkinsfile` is fine to do as a PR but it must be done by someone with repository write access, so that merging can be delayed until all tests are passing. Otherwise we wind up with broken builds in `master` and other PRs, currently under correction in #117.

**Pull request merged**
