### PR TITLE
[JENKINS-30117] Support bundle blocks with lots of data

### PR DESCRIPTION
**Pull request by christ66**
The format method should be thread safe as it could be invoked from
multiple threads. Instead of using a MessageFormatter which is not thread safe we
use the FastDateFormatter, and a StringBuffer both of which are thread
safe.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:ant: <code>StringBuffer</code> is not required here from what I see. You use it in a method internally => it operates within one thread => It makes sense to replace it to <code>StringBuilder</code> for the sake of the better performance.

**Comment by rsandell** [comment]
:bee:

**Comment by christ66** [comment]
@oleg-nenashev I think you're right. It should be using `StringBuilder`.

**Comment by christ66** [comment]
@oleg-nenashev fixed.

**Comment by stephenc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by jtnord** [comment]
:bee:

**Pull request merged**
