### PR TITLE
update uadetector-resources from 2013.09 to 2014.10

### PR DESCRIPTION
**Pull request by based2**
This package contains a verified version of the data file from http://user-agent-string.info

https://mvnrepository.com/artifact/net.sf.uadetector/uadetector-resources

### CODE REVIEW

**Comment by aheritier** [comment]
Should be safe I think cc @batmat @MRamonLeon

**Comment by aheritier** [comment]
Replacing something very very very old by something very vry old

https://github.com/before/uadetector/releases

**Comment by varyvol** [comment]
@based2 could you please explain what issue this helps to solve?

**Comment by varyvol** [comment]
Closing due to inactivity. Please feel free to reopen if you work on this again.

**Pull request closed without merging**
