### PR TITLE
[JENKINS-28703] Add pinned status for plugins.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:+1:

**Comment by ydubreuil** [comment]
:-1:
It's lacking a separator between version and pin status, will not be able to parse content without an additional ":"

**Comment by christ66** [comment]
@ydubreuil fixed.

**Comment by ydubreuil** [comment]
:+1:

**Comment by jtnord** [comment]
:+1:

**Pull request merged**
