### PR TITLE
PSE Support Bundle

### PR DESCRIPTION
**Pull request by spnchian**
Added an action that will make it easier for PSE to request a support bundle from the Support Core Plugin. The added action is very similar to doDownload in the way it generates the support bundle.

### CODE REVIEW

**Comment by spnchian** [comment]
@reviewbybees

**Comment by Vlatombe** [comment]
🐛  support-core shouldn't mention PSE at all. Given your new method takes the same parameters as the doDownload method and is roughly making components optional, I would refactor the `doDownload` to do what you need.

**Comment by aheritier** [comment]
Yes support-core must remain generic. If required you can add new extension points. At CloudBees we have a specific plugin implementing these extension points to manage everything which is specific to our product

**Comment by stephenc** [comment]
If this is a CloudBees specific generic extension it should go in CloudBees-support

If this is a PSE specific extension the PSE should host it in either a specific CloudBees-PSE-support plugin or in an existing PSE plugin

:bug: on this code going here

**Comment by jglick** [comment]
This is not an extension, it is an alternate download mode. :bug: as per @Vlatombe.

**Comment by oleg-nenashev** [comment]
🐛 to just join the party. Private-source extensions do not belong to OSS

**Comment by spnchian** [comment]
As stated above, this was originally written to be an alternate download. I am trying to access this plugin using curl commands and unfortunately, the form submission format was not working in the `doDownload`. I can't seem to be able to format the form correctly to allow the curl command to be processed through. Could someone give an example of what would work?

**Comment by spnchian** [comment]
Nevermind. I got it to work.

**Pull request closed without merging**
