### PR TITLE
bump jenkins version and bom

### PR DESCRIPTION
**Pull request by jetersen**
Once more for credentials plugin 😅 

`2.80.2` would be great. Let me test the incremental first though to verify.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jetersen** [comment]
@Dohbedoh can confirm 2.319.x bump solves the problems we have in bom: https://github.com/jenkinsci/bom/pull/1275

Would appreciate another release 2.80.2, sorry should have confirmed with the incremental!

**Review by jglick — APPROVED** [review]

**Comment by jetersen** [comment]
:shipit: ? 😅

**Comment by jglick** [comment]
Usually @Dohbedoh would approve I think.

**Review by Dohbedoh — APPROVED** [review]

**Comment by Dohbedoh** [comment]
@jetersen released https://github.com/jenkinsci/support-core-plugin/releases/tag/support-core-2.80.2

**Pull request merged**
