### PR TITLE
[JENKINS-64549] Use PowerMockito and versions from plugin-pom

### PR DESCRIPTION
**Pull request by Dohbedoh**
[JENKINS-64549](https://issues.jenkins.io/browse/JENKINS-64549) Upgrade to Mockito is failing on the mock of a static inner class. Switching to PowerMockito and the version managed in plugin-pom.

Amends https://github.com/jenkinsci/support-core-plugin/pull/262

### CODE REVIEW

**Comment by batmat** [comment]
Seems tests are failing?

**Comment by Dohbedoh** [comment]
PowerMockito does not handle `AssumptionViolatedException` properly https://github.com/powermock/powermock/issues/428... Will refactor the tests.

**Comment by Dohbedoh** [comment]
@batmat Refactored the tests to not use Assume that is not supported by `PowerMockitoRunner`. Now each tests have an if statement depending on whether java version is <= 8 or not.

**Comment by batmat** [comment]
Seems PR is still failing? Retriggering just in case (no time just now to check the build and the actual reason).

**Comment by batmat** [comment]
removing my review request for now. Please feel free to add me again when the PR goes green. Thanks!

**Comment by Dohbedoh** [comment]
@batmat The build is passing since Jan 18 actually https://ci.jenkins.io/job/Plugins/job/support-core-plugin/job/PR-264/. The GitHub status `continuous-integration/jenkins/pr-merge` is not being updated by the CI and still pointing to older build #4 (newer PR do not use this status anymore)

So looks like all is green.

**Pull request merged**
