### PR TITLE
Add root Jenkins config.xml to support bundle

### PR DESCRIPTION
**Pull request by joshshinn**
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:-1:, this could contain private information, and could be huge if (prior to 1.607 IIRC) there are a lot of slaves.

Any basic information is already in `about.md`.

**Comment by christ66** [comment]
What if we disabled it by default? I still think having the option to download this via support bundle is useful.

**Comment by jglick** [comment]
Is it not much more common to want job `config.xml`s? I mean, you can always request particular files you know you are interested in.

**Comment by stephenc** [comment]
:-1: too much of a security risk, better to just ask for the file if you need it

**Comment by stephenc** [comment]
Closing as maintainer

**Pull request closed without merging**
