### PR TITLE
System conf enhancement

### PR DESCRIPTION
**Pull request by ydubreuil**
This PR adds 2 features:

* add system uptime to see if an outage comes from a system reboot
* add DMI information to see if Jenkins is running on a virtualized server

@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
:+1: for the principle... you have a findbugs to fix

**Comment by ndeloof** [comment]
:+1:

**Comment by ydubreuil** [comment]
I've fixed the findbugs and push forced my change as it's a one-liner

**Comment by jglick** [comment]
:+1:

**Comment by christ66** [comment]
:+1:

**Pull request merged**
