### PR TITLE
JENKINS-42512 - "Slave" is replaced with Agent.

### PR DESCRIPTION
**Pull request by duemir**
Java elements and bundle structure is not touched for compatibility.
UI and comments are updated.

@reviewbybees

### CODE REVIEW

**Comment by duemir** [comment]
@stephenc you mentioned as a maintainer on the wiki. It's minor straightforward change. Can I get a second bee and a merge? :)

**Comment by stephenc** [comment]
CloudBees support took over. Long time since I cut a release. Suggest finding out off @aheritier who to ping

**Comment by batmat** [comment]
Merging as this is a minor change and somehow already pre-agreed per Jenkins 2.x.

@stephenc do you think removing you from the pom.xml/developers would be good so that you don't appear anymore on the wiki macro as a maintainer?

**Comment by aheritier** [comment]
@christ66 is still around if we need. CloudBees support didn't take over it even if Steven was the most active recently. All others contributors are welcomed.

**Comment by christ66** [comment]
I'm still around 😄 .

Maybe we should create a Jenkinsfile which can perform a release after every merge request just in case I'm not around to complete it.

WRT the PR, 👍 .

**Pull request merged**
