### PR TITLE
JENKINS-34462 - Support core plugin needs to obtain the status of whether CSRF protection is enabled

### PR DESCRIPTION
**Pull request by Evildethow**
@reviewbybees

### CODE REVIEW

**Comment by Dohbedoh** [comment]
:bee:

**Comment by mslusarczyk** [comment]
🐝 
what do you think about putting it in 'Important configuration' section ?

**Comment by christ66** [comment]
:bug: as this could lead to a NPE (http://javadoc.jenkins-ci.org/jenkins/model/JenkinsLocationConfiguration.html#get()). Instead I recommend doing `Helper.getActiveInstance()` which never returns null and will instead throw a RTE (https://github.com/jenkinsci/support-core-plugin/blob/master/src/main/java/com/cloudbees/jenkins/support/util/Helper.java#L20-L21)

I agree with @mslusarczyk that this is a security configuration, so it should be in the important configuration section.

**Comment by Evildethow** [comment]
@christ66 @mslusarczyk Agreed.

**Comment by Evildethow** [comment]
@christ66 @mslusarczyk Code review changes made. Let me know if you are happy and ill rebase to clean up the extra commit.

**Comment by mslusarczyk** [comment]
lgtm 🐝

**Comment by christ66** [comment]
:bee:

**Pull request merged**
